### ISSUE TITLE
EDA only supports types "srl" and "sros"

### ISSUE THREAD

**Issue by FloSch62** [eda-labs/clab-connector#4]
Example node profile generated when node type in the topology file is set to nokia_srlinux:
This is not OK, since the "operatingSystem" can only be srl.

```
metadata:
  name: eda-lab-srlinux-24.7.2
spec:
  port: 57400
  transport: GNMI
  operatingSystem: nokia_srlinux
  version: 24.7.2
  versionPath: .system.information.version
  versionMatch: v24\.7\.2.*
  yang: https://eda-asvr/schemaprofiles/srlinux-ghcr-24.7.2/srlinux-24.7.2.zip
  nodeUser: admin
  dhcp:
    managementPoolv4: 'eda-lab-mgmt-pool'
  gnmiOptions:
    annotate: false
    commitConfirmed: true
    configSubscription: true
  images:
  - image: srlimages/srlinux-24.7.2-bin/srlinux.bin
    imageMd5: srlimages/srlinux-24.7.2-bin/srlinux.bin.md5
```
![image](https://github.com/user-attachments/assets/652479ca-16d8-4542-b86f-c074f4c32487)
